event:
  name: "Simpósio Semana do Farmacêutico"
  url: "https://crfam.org.br"
  date: "17 a 20 de Janeiro 2022"
  duration: "4 Horas"
site:
  lang: "pt-br"
  title: "Simpósio Semana do Farmacêutico"
  logo: "static/images/logo.png"
  index:
    message: "Informe o número do seu CPF"
    emailPlaceholder: "E-mail"
    cpfPlaceholder: "Digite o CPF. Somente números."
    inputLabel: "CPF"
    submit: "Gerar"
certificate:
  logo: "static/images/logo.png"
  background: "static/images/background.jpeg"
  textLine1: "Você é um herói da Farmácia!"
  textLine2: "Se o Amazonas está superando a Covid- 19, o papel do farmacêutico é fundamental. E nós, do Conselho Regional de Farmácia do Amazonas, neste Dia Internacional do Farmacêutico, reconhecemos, por meio deste certificado, a importância do seu trabalho e da sua dedicação. Parabéns por representar de maneira tão honrada a profissão farmacêutica."
  
routes:
  certificate: certificado
errors:
  error: "<strong>Error:</strong> %message%"
  missingEmail: "CPF não encontrado!"
  invalidEmail: "CPF não encontrado!"
  emailNoExists: "CPF não encontrado!"
  notAttended: "You did not attended to this!"
  csvError: "Erro na leitura do arquivo CSV!"
  csrfError: "Cheatin' huh?"
  error404: "404: Página não encontrada"
  error500: "500: Erro no servidor"
csv: csv/sample.csv